### ISSUE TITLE
Cannot register plugin

### ISSUE THREAD

**Issue by huynhlebaoanh** [stelgenhof/homebridge-ailight#3]
I installed plug-in and modified config file as sample config. But this message showed when I restarted homebridge
Error: The requested accessory 'AiLight' was not registered by any plugin.

**Comment by stelgenhof** [comment]
@huynhlebaoanh Sorry to hear about the issue you had. Could you provide a bit more information? For example what version of the plugin you are using, the homebridge version? Also a complete error log would be very helpful.

Thanks! Sacha
